import Link from 'next/link';
import { ArrowRight, BarChart3, Bot, Shield, Zap, Globe, TrendingUp } from 'lucide-react';

export default function HomePage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-latrux-darker via-latrux-dark to-latrux-darker">
      {/* Nav */}
      <nav className="border-b border-border/40 backdrop-blur-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Zap className="h-8 w-8 text-latrux-gold" />
            <span className="text-xl font-bold bg-gradient-to-r from-latrux-gold to-yellow-300 bg-clip-text text-transparent">
              LatruxTrade
            </span>
          </div>
          <div className="flex items-center gap-4">
            <Link href="/community" className="text-sm text-muted-foreground hover:text-foreground transition">
              Community
            </Link>
            <Link href="/subscriptions" className="text-sm text-muted-foreground hover:text-foreground transition">
              Pricing
            </Link>
            <Link
              href="/auth/signin"
              className="text-sm px-4 py-2 rounded-lg bg-secondary hover:bg-secondary/80 transition"
            >
              Sign In
            </Link>
            <Link
              href="/auth/signup"
              className="text-sm px-4 py-2 rounded-lg bg-latrux-gold text-black font-semibold hover:bg-latrux-gold/90 transition"
            >
              Get Started
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="max-w-7xl mx-auto px-4 pt-24 pb-16 text-center">
        <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-latrux-gold/10 border border-latrux-gold/20 text-latrux-gold text-sm mb-8">
          <Bot className="h-4 w-4" />
          Powered by Latrux AI — God-Tier Autonomous Brain
        </div>
        <h1 className="text-5xl md:text-7xl font-bold tracking-tight mb-6">
          <span className="bg-gradient-to-r from-white via-gray-200 to-gray-400 bg-clip-text text-transparent">
            Trade Smarter.
          </span>
          <br />
          <span className="bg-gradient-to-r from-latrux-gold via-yellow-300 to-latrux-gold bg-clip-text text-transparent">
            Trade Autonomous.
          </span>
        </h1>
        <p className="text-lg text-muted-foreground max-w-2xl mx-auto mb-10">
          AI-generated signals, automated execution, and institutional-grade analytics.
          LatruxTrade is the self-evolving trading ecosystem that works while you sleep.
        </p>
        <div className="flex items-center justify-center gap-4">
          <Link
            href="/auth/signup"
            className="inline-flex items-center gap-2 px-8 py-3 rounded-lg bg-latrux-gold text-black font-bold text-lg hover:bg-latrux-gold/90 transition shadow-lg shadow-latrux-gold/25"
          >
            Start Trading Free <ArrowRight className="h-5 w-5" />
          </Link>
          <Link
            href="/dashboard"
            className="inline-flex items-center gap-2 px-8 py-3 rounded-lg border border-border hover:bg-secondary transition text-lg"
          >
            View Dashboard
          </Link>
        </div>
      </section>

      {/* Features */}
      <section className="max-w-7xl mx-auto px-4 py-24">
        <h2 className="text-3xl font-bold text-center mb-16">Why LatruxTrade?</h2>
        <div className="grid md:grid-cols-3 gap-8">
          {[
            {
              icon: <Bot className="h-10 w-10 text-latrux-gold" />,
              title: 'AI-Powered Signals',
              desc: 'Binary, scalping, and swing signals generated by Latrux AI with 5-indicator confluence scoring.',
            },
            {
              icon: <BarChart3 className="h-10 w-10 text-latrux-blue" />,
              title: 'Advanced Charts',
              desc: '200+ indicators, real-time data, and proprietary Canvas/WebGL rendering engine.',
            },
            {
              icon: <TrendingUp className="h-10 w-10 text-latrux-green" />,
              title: 'Paper Trading',
              desc: 'Execute signals risk-free. Track positions, P&L, and build confidence before going live.',
            },
            {
              icon: <Shield className="h-10 w-10 text-latrux-purple" />,
              title: 'Iron Dome Security',
              desc: 'Enterprise-grade security with encrypted wallets, KYC verification, and fraud detection.',
            },
            {
              icon: <Globe className="h-10 w-10 text-latrux-blue" />,
              title: 'Global Community',
              desc: 'Join traders worldwide. Copy top performers, share strategies, earn affiliate commissions.',
            },
            {
              icon: <Zap className="h-10 w-10 text-latrux-gold" />,
              title: 'Maker Engine',
              desc: 'Connect 10,000+ brokers. Visual API connector with automated trade execution.',
            },
          ].map((f, i) => (
            <div key={i} className="p-6 rounded-xl border bg-card hover:border-latrux-gold/30 transition group">
              <div className="mb-4">{f.icon}</div>
              <h3 className="text-lg font-semibold mb-2">{f.title}</h3>
              <p className="text-sm text-muted-foreground">{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Pricing Preview */}
      <section className="max-w-7xl mx-auto px-4 py-24 text-center">
        <h2 className="text-3xl font-bold mb-4">Plans for Every Trader</h2>
        <p className="text-muted-foreground mb-12">From free to institutional. Scale as you grow.</p>
        <div className="grid md:grid-cols-4 gap-6">
          {[
            { name: 'Light', price: 'Free', signals: '3/day' },
            { name: 'AI Trader', price: '$49/mo', signals: '50/day', popular: true },
            { name: 'Elite', price: '$149/mo', signals: '200/day' },
            { name: 'Institutional', price: '$999+/mo', signals: 'Unlimited' },
          ].map((p, i) => (
            <div
              key={i}
              className={`p-6 rounded-xl border ${
                p.popular ? 'border-latrux-gold glow-gold' : 'border-border'
              } bg-card relative`}
            >
              {p.popular && (
                <div className="absolute -top-3 left-1/2 -translate-x-1/2 px-3 py-0.5 rounded-full bg-latrux-gold text-black text-xs font-bold">
                  Most Popular
                </div>
              )}
              <h3 className="text-lg font-semibold mb-2">{p.name}</h3>
              <div className="text-3xl font-bold mb-4">{p.price}</div>
              <p className="text-sm text-muted-foreground">{p.signals} signals</p>
              <Link
                href="/subscriptions"
                className="mt-4 inline-block w-full py-2 rounded-lg bg-secondary hover:bg-secondary/80 transition text-sm"
              >
                View Details
              </Link>
            </div>
          ))}
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border/40 py-12">
        <div className="max-w-7xl mx-auto px-4 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Zap className="h-5 w-5 text-latrux-gold" />
            <span className="font-semibold text-sm">LatruxTrade</span>
          </div>
          <p className="text-xs text-muted-foreground">
            Director: Tatenda Christopher Muto | Powered by Latrux AI
          </p>
        </div>
      </footer>
    </div>
  );
}
